"""Auto-generated by Pipeline D (handwritten_dispatch) — a self-contained,
dispatch-free Triton program for one AtenIR graph.

Only the Triton kernels actually used by this graph are included below (pulled
transitively from atenir/primitive_triton/), wrapped in an EVOLVE-BLOCK so
OpenEvolve can rewrite/fuse them. There is no string-matching op dispatch table
and no runtime registry: every call in `run_graph_program` below the block is a
direct call to one of these kernels, with any baked scalar arguments inlined as
literal defaults.

`run_graph_program` is the literal, unrolled call sequence for this graph — one
statement per AtenIR call_function node, in topological order.
"""

from __future__ import annotations

import torch
import triton
import triton.language as tl
import triton.language.extra.cuda.libdevice as libdevice

# EVOLVE-BLOCK-START

HAS_TRITON = True
_BLOCK = 1024


def _row_sum(a: torch.Tensor, keepdim: bool) -> torch.Tensor:
    return _row_reduce(a, _row_sum_kernel, a.dtype, keepdim)


def _row_reduce(a: torch.Tensor, kernel, out_dtype, keepdim: bool) -> torch.Tensor:
    assert a.ndim == 2
    a = a.contiguous()
    R, C = a.shape
    out = torch.empty(R, device=a.device, dtype=out_dtype)
    BLOCK_C = min(_next_pow2(C), 65536)
    kernel[R,](a, out, R, C, BLOCK_C=BLOCK_C)
    return out.unsqueeze(1) if keepdim else out


def _next_pow2(n: int) -> int:
    p = 1
    while p < n:
        p <<= 1
    return p


@triton.jit
def _row_sum_kernel(a_ptr, out_ptr, R, C, BLOCK_C: tl.constexpr):
    """sum([R, C], dim=1) → [R]  (one program per row)."""
    row = tl.program_id(0)
    cols = tl.arange(0, BLOCK_C)
    mask = cols < C
    a = tl.load(a_ptr + row * C + cols, mask=mask, other=0.0)
    tl.store(out_ptr + row, tl.sum(a.to(tl.float32), axis=0).to(a.dtype))


def div_scalar(a: torch.Tensor, scalar) -> torch.Tensor:
    a = a.contiguous()
    out = torch.empty_like(a)
    _div_scalar_kernel[_grid(a.numel())](a, out, float(scalar), N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _div_scalar_kernel(a_ptr, out_ptr, scalar, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, a / scalar, mask=mask)


def _grid(n: int):
    import math

    return (math.ceil(n / _BLOCK),)


def _col_sum(a: torch.Tensor, keepdim: bool) -> torch.Tensor:
    return _col_reduce(a, _col_sum_kernel, a.dtype, keepdim)


def _col_reduce(a: torch.Tensor, kernel, out_dtype, keepdim: bool) -> torch.Tensor:
    assert a.ndim == 2
    a = a.contiguous()
    R, C = a.shape
    out = torch.empty(C, device=a.device, dtype=out_dtype)
    BLOCK_R = min(_next_pow2(R), 65536)
    kernel[C,](a, out, R, C, BLOCK_R=BLOCK_R)
    return out.unsqueeze(0) if keepdim else out


@triton.jit
def _col_sum_kernel(a_ptr, out_ptr, R, C, BLOCK_R: tl.constexpr):
    """sum([R, C], dim=0) → [C]  (one program per column)."""
    col = tl.program_id(0)
    rows = tl.arange(0, BLOCK_R)
    mask = rows < R
    a = tl.load(a_ptr + rows * C + col, mask=mask, other=0.0)
    tl.store(out_ptr + col, tl.sum(a.to(tl.float32), axis=0).to(a.dtype))


def sub_tt(a: torch.Tensor, b: torch.Tensor, alpha: float = 1.0) -> torch.Tensor:
    a, b = _bc(a, b)
    out = torch.empty_like(a)
    if alpha != 1.0:
        b = mul_scalar(b, alpha)
    _sub_kernel[_grid(a.numel())](a, b, out, N=a.numel(), BLOCK=_BLOCK)
    return out


def _bc(*tensors):
    """Broadcast all tensors to a common shape and make contiguous."""
    broadcast = torch.broadcast_tensors(*tensors)
    return tuple((t.contiguous() for t in broadcast))


def mul_scalar(a: torch.Tensor, scalar) -> torch.Tensor:
    a = a.contiguous()
    out = torch.empty_like(a)
    _mul_scalar_kernel[_grid(a.numel())](a, out, float(scalar), N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _mul_scalar_kernel(a_ptr, out_ptr, scalar, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, a * scalar, mask=mask)


@triton.jit
def _sub_kernel(a_ptr, b_ptr, out_ptr, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    b = tl.load(b_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, a - b, mask=mask)


def pow_scalar(a: torch.Tensor, exp) -> torch.Tensor:
    a = a.contiguous()
    exp_f = float(exp)
    if exp_f == 0.0:
        return torch.ones_like(a)
    if exp_f == 1.0:
        return a.clone()
    if exp_f == 2.0:
        return mul_tt(a, a)
    if exp_f == 3.0:
        return mul_tt(mul_tt(a, a), a)
    out = torch.empty_like(a, dtype=torch.float32)
    _pow_scalar_kernel[_grid(a.numel())](a, out, exp_f, N=a.numel(), BLOCK=_BLOCK)
    return out.to(a.dtype)


def mul_tt(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    a, b = _bc(a, b)
    out = torch.empty_like(a)
    _mul_kernel[_grid(a.numel())](a, b, out, N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _mul_kernel(a_ptr, b_ptr, out_ptr, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    b = tl.load(b_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, a * b, mask=mask)


@triton.jit
def _pow_scalar_kernel(a_ptr, out_ptr, exp, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=1.0).to(tl.float32)
    tl.store(out_ptr + offs, tl.exp(exp * tl.log(a)), mask=mask)


def add_scalar(a: torch.Tensor, scalar) -> torch.Tensor:
    a = a.contiguous()
    out = torch.empty_like(a)
    _add_scalar_kernel[_grid(a.numel())](a, out, float(scalar), N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _add_scalar_kernel(a_ptr, out_ptr, scalar, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, a + scalar, mask=mask)


def rsqrt(a: torch.Tensor) -> torch.Tensor:
    a = a.contiguous()
    out = torch.empty_like(a)
    _rsqrt_kernel[_grid(a.numel())](a, out, N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _rsqrt_kernel(a_ptr, out_ptr, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=1.0).to(tl.float32)
    tl.store(out_ptr + offs, 1.0 / tl.sqrt(a), mask=mask)


def add_tt(a: torch.Tensor, b: torch.Tensor, alpha: float = 1.0) -> torch.Tensor:
    a, b = _bc(a, b)
    out = torch.empty_like(a)
    if alpha != 1.0:
        b = mul_scalar(b, alpha)
    _add_kernel[_grid(a.numel())](a, b, out, N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _add_kernel(a_ptr, b_ptr, out_ptr, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    b = tl.load(b_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, a + b, mask=mask)


def neg(a: torch.Tensor) -> torch.Tensor:
    a = a.contiguous()
    out = torch.empty_like(a)
    _neg_kernel[_grid(a.numel())](a, out, N=a.numel(), BLOCK=_BLOCK)
    return out


@triton.jit
def _neg_kernel(a_ptr, out_ptr, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    tl.store(out_ptr + offs, -a, mask=mask)


def _k0(a):
    return a.contiguous()


def _k1(a: torch.Tensor, _dims=[-1], _keepdim=True) -> torch.Tensor:
    if HAS_TRITON and a.ndim == 2:
        R, C = a.shape
        dims_norm = [d % a.ndim for d in _dims]
        if dims_norm == [1]:
            total = _row_sum(a, _keepdim)
            return div_scalar(total, float(C))
        if dims_norm == [0]:
            total = _col_sum(a, _keepdim)
            return div_scalar(total, float(R))
    return a.mean(dim=_dims if _dims else None, keepdim=_keepdim)


def _k2(a, exp_val=2.0):
    return pow_scalar(a, exp_val)


def _k3(a, s=1e-05):
    return add_scalar(a, s)


def _k4(a: torch.Tensor, _dims=[0], _keepdim=True) -> torch.Tensor:
    if HAS_TRITON and a.ndim == 2:
        dims_norm = [d % a.ndim for d in _dims]
        if dims_norm == [1]:
            return _row_sum(a, _keepdim)
        if dims_norm == [0]:
            return _col_sum(a, _keepdim)
    return a.sum(dim=_dims if _dims else None, keepdim=_keepdim)


def _k5(a, shape=[64]):
    return a.reshape(shape).contiguous()


def _k6(a: torch.Tensor, _dims=[1], _keepdim=True) -> torch.Tensor:
    if HAS_TRITON and a.ndim == 2:
        dims_norm = [d % a.ndim for d in _dims]
        if dims_norm == [1]:
            return _row_sum(a, _keepdim)
        if dims_norm == [0]:
            return _col_sum(a, _keepdim)
    return a.sum(dim=_dims if _dims else None, keepdim=_keepdim)


def _k7(a, s=-0.5):
    return mul_scalar(a, s)


def _k8(a, exp_val=3.0):
    return pow_scalar(a, exp_val)


def _k9(a, shape=[8, 64]):
    return a.expand(tuple(shape)).contiguous()


def _k10(a, s=64.0):
    return div_scalar(a, s)


def _k11(a, exp_val=1.0):
    return pow_scalar(a, exp_val)


def _k12(a, s=2.0):
    return mul_scalar(a, s)


# EVOLVE-BLOCK-END


def run_graph_program(t_arg0_1, t_arg1_1, t_arg2_1, t_arg3_1):
    t_alias = _k0(t_arg1_1)  # alias: aten.alias.default
    t_alias_1 = _k0(t_arg2_1)  # alias_1: aten.alias.default
    t_alias_2 = _k0(t_arg3_1)  # alias_2: aten.alias.default
    t_mean = _k1(t_alias)  # mean: aten.mean.dim
    t_sub = sub_tt(t_alias, t_mean)  # sub: aten.sub.Tensor
    t_pow_1 = _k2(t_sub)  # pow_1: aten.pow.Tensor_Scalar
    t_mean_1 = _k1(t_pow_1)  # mean_1: aten.mean.dim
    t_sub_1 = sub_tt(t_alias, t_mean)  # sub_1: aten.sub.Tensor
    t_add = _k3(t_mean_1)  # add: aten.add.Tensor
    t_rsqrt = rsqrt(t_add)  # rsqrt: aten.rsqrt.default
    t_alias_3 = _k0(t_rsqrt)  # alias_3: aten.alias.default
    t_mul = mul_tt(t_sub_1, t_rsqrt)  # mul: aten.mul.Tensor
    t_mul_1 = mul_tt(t_mul, t_alias_1)  # mul_1: aten.mul.Tensor
    t_add_1 = add_tt(t_mul_1, t_alias_2)  # add_1: aten.add.Tensor
    t_sum_1 = _k4(t_arg0_1)  # sum_1: aten.sum.dim_IntList
    t_view = _k5(t_sum_1)  # view: aten.view.default
    t_mul_2 = mul_tt(t_arg0_1, t_mul)  # mul_2: aten.mul.Tensor
    t_mul_3 = mul_tt(t_arg0_1, t_alias_1)  # mul_3: aten.mul.Tensor
    t_sum_2 = _k4(t_mul_2)  # sum_2: aten.sum.dim_IntList
    t_view_1 = _k5(t_sum_2)  # view_1: aten.view.default
    t_mul_4 = mul_tt(t_mul_3, t_sub_1)  # mul_4: aten.mul.Tensor
    t_mul_5 = mul_tt(t_mul_3, t_rsqrt)  # mul_5: aten.mul.Tensor
    t_sum_3 = _k6(t_mul_4)  # sum_3: aten.sum.dim_IntList
    t_alias_4 = _k0(t_alias_3)  # alias_4: aten.alias.default
    t_mul_6 = _k7(t_sum_3)  # mul_6: aten.mul.Scalar
    t_pow_2 = _k8(t_alias_4)  # pow_2: aten.pow.Tensor_Scalar
    t_mul_7 = mul_tt(t_mul_6, t_pow_2)  # mul_7: aten.mul.Tensor
    t_neg = neg(t_mul_5)  # neg: aten.neg.default
    t_sum_4 = _k6(t_neg)  # sum_4: aten.sum.dim_IntList
    t_expand = _k9(t_mul_7)  # expand: aten.expand.default
    t_div = _k10(t_expand)  # div: aten.div.Scalar
    t_pow_3 = _k11(t_sub)  # pow_3: aten.pow.Tensor_Scalar
    t_mul_8 = _k12(t_pow_3)  # mul_8: aten.mul.Scalar
    t_mul_9 = mul_tt(t_div, t_mul_8)  # mul_9: aten.mul.Tensor
    t_neg_1 = neg(t_mul_9)  # neg_1: aten.neg.default
    t_sum_5 = _k6(t_neg_1)  # sum_5: aten.sum.dim_IntList
    t_add_2 = add_tt(t_mul_5, t_mul_9)  # add_2: aten.add.Tensor
    t_add_3 = add_tt(t_sum_4, t_sum_5)  # add_3: aten.add.Tensor
    t_expand_1 = _k9(t_add_3)  # expand_1: aten.expand.default
    t_div_1 = _k10(t_expand_1)  # div_1: aten.div.Scalar
    t_add_4 = add_tt(t_add_2, t_div_1)  # add_4: aten.add.Tensor
    return (t_add_4, t_view_1, t_view)
