"""
Materialize a unified phase's initial_program.py with a literal dict
containing the union of prior-phase winners (from shared/phaseN_best.json).

Per-bench `prepare_phase_unified.py` wrappers call
`main(root, shared, prior_phases, unified_file)` after all prior phases
have completed (and extract_best.py ran for each).

Rewrites only the EVOLVE-BLOCK section of the unified phase's initial_program.py.
"""
import json
import pathlib
import pprint
import re
import sys

_EVOLVE_BLOCK_RE = re.compile(
    r"(# EVOLVE-BLOCK-START\n).*?(# EVOLVE-BLOCK-END)",
    re.DOTALL,
)


def _load(shared, n):
    f = pathlib.Path(shared) / f"phase{n}_best.json"
    if not f.exists():
        print(f"missing: {f}", file=sys.stderr)
        sys.exit(1)
    return json.loads(f.read_text())


def main(root, shared, prior_phases, unified_file, dict_name="UNIFIED_OVERRIDES"):
    """
    root           — bench evolve dir (pathlib.Path)
    shared         — bench evolve/shared dir (pathlib.Path)
    prior_phases   — list of phase ints to merge (e.g. [1, 2, 3])
    unified_file   — path to the unified phase's initial_program.py
    dict_name      — variable name written in the EVOLVE-BLOCK (default UNIFIED_OVERRIDES)
    """
    unified_file = pathlib.Path(unified_file)
    merged = {}
    phase_counts = {}
    for n in prior_phases:
        d = _load(shared, n)
        phase_counts[n] = len(d)
        merged.update(d)
    print("merged keys: " + " ".join(f"p{n}={c}" for n, c in phase_counts.items())
          + f" union={len(merged)}")

    src = unified_file.read_text()
    dict_repr = pprint.pformat(merged, width=100, sort_dicts=True)
    new_block_body = (
        "# Auto-generated by prepare_phase_unified.py from union of prior phase winners.\n"
        f"{dict_name} = {dict_repr}\n"
    )
    new_src, n_subs = _EVOLVE_BLOCK_RE.subn(
        lambda m: m.group(1) + new_block_body + m.group(2),
        src,
        count=1,
    )
    if n_subs != 1:
        print(f"EVOLVE-BLOCK markers not found in {unified_file}", file=sys.stderr)
        sys.exit(1)
    unified_file.write_text(new_src)
    print(f"wrote {unified_file.relative_to(pathlib.Path(root))} "
          f"({len(merged)} keys in EVOLVE-BLOCK)")
