"""
Materialize a unified phase's initial_program.py with the union of prior-phase
winners (from shared/phaseN_best.json + optional phaseN_buckets.json +
phaseN_stage3.json).

Per-bench `prepare_phase_unified.py` wrappers call
`main(root, shared, prior_phases, unified_file)` after all prior phases
have completed (and extract_best.py ran for each).

Rewrites only the EVOLVE-BLOCK section of the unified phase's initial_program.py.

Output format inside EVOLVE-BLOCK (cpsat-bench layout):
    GLOBAL_OVERRIDES = {...}            # union of phaseN_best.json
    SIZE_BUCKETS     = [(upper, {...})] # merged per-bucket overrides
    STAGE3_OVERRIDES = {...}            # union of phaseN_stage3.json

If a bench doesn't ship the bucket/stage3 files, only GLOBAL_OVERRIDES is
written (legacy single-dict layout) — controlled by `dict_name` parameter.
"""
import json
import pathlib
import pprint
import re
import sys

_EVOLVE_BLOCK_RE = re.compile(
    r"(# EVOLVE-BLOCK-START\n).*?(# EVOLVE-BLOCK-END)",
    re.DOTALL,
)


def _load(shared, n):
    f = pathlib.Path(shared) / f"phase{n}_best.json"
    if not f.exists():
        print(f"missing: {f}", file=sys.stderr)
        sys.exit(1)
    return json.loads(f.read_text())


def _maybe_load(shared, name):
    f = pathlib.Path(shared) / name
    if not f.exists():
        return None
    return json.loads(f.read_text())


def _merge_buckets(prior_buckets_list):
    """Merge a list of bucket-lists (one per phase) into a single
    list[(upper, dict)], ordered by ascending upper (None == inf last).
    Phases later in the list win on key conflicts within the same bucket."""
    # Collect all unique upper bounds, preserving inf -> None.
    by_upper = {}
    order_seen = []
    for blist in prior_buckets_list:
        if not blist:
            continue
        for upper, override in blist:
            key = upper  # None for inf, numeric otherwise
            if key not in by_upper:
                by_upper[key] = {}
                order_seen.append(key)
            by_upper[key].update(override)

    def _sort_key(k):
        return float("inf") if k is None else k

    return [[k, by_upper[k]] for k in sorted(by_upper.keys(), key=_sort_key)]


def _format_buckets_literal(buckets):
    """Render bucket list as Python source. None upper -> float('inf')."""
    lines = ["["]
    for upper, override in buckets:
        upper_src = "float('inf')" if upper is None else repr(upper)
        ov_src = pprint.pformat(override, width=100, sort_dicts=True)
        lines.append(f"    ({upper_src}, {ov_src}),")
    lines.append("]")
    return "\n".join(lines)


def main(root, shared, prior_phases, unified_file, dict_name="UNIFIED_OVERRIDES"):
    """
    root           — bench evolve dir (pathlib.Path)
    shared         — bench evolve/shared dir (pathlib.Path)
    prior_phases   — list of phase ints to merge (e.g. [1, 2, 3])
    unified_file   — path to the unified phase's initial_program.py
    dict_name      — variable name for the merged global dict. Default
                     "UNIFIED_OVERRIDES" (legacy). cpsat-bench unified phase
                     uses "GLOBAL_OVERRIDES"; pass dict_name="GLOBAL_OVERRIDES"
                     from the wrapper.
    """
    unified_file = pathlib.Path(unified_file)

    merged = {}
    phase_counts = {}
    prior_buckets = []
    merged_stage3 = {}
    phase_stage3_counts = {}

    for n in prior_phases:
        d = _load(shared, n)
        phase_counts[n] = len(d)
        merged.update(d)

        b = _maybe_load(shared, f"phase{n}_buckets.json")
        if b is not None:
            prior_buckets.append(b)

        s = _maybe_load(shared, f"phase{n}_stage3.json")
        if isinstance(s, dict):
            phase_stage3_counts[n] = len(s)
            merged_stage3.update(s)

    print("merged keys: " + " ".join(f"p{n}={c}" for n, c in phase_counts.items())
          + f" union={len(merged)}")

    has_extras = bool(prior_buckets) or bool(merged_stage3)

    src = unified_file.read_text()

    if has_extras:
        merged_buckets = _merge_buckets(prior_buckets)
        nonempty = sum(1 for _, d in merged_buckets if d)
        if phase_stage3_counts:
            print("stage3 keys: "
                  + " ".join(f"p{n}={c}" for n, c in phase_stage3_counts.items())
                  + f" union={len(merged_stage3)}")
        print(f"size buckets: {len(merged_buckets)} entries ({nonempty} non-empty)")

        dict_repr = pprint.pformat(merged, width=100, sort_dicts=True)
        buckets_repr = _format_buckets_literal(merged_buckets)
        stage3_repr = pprint.pformat(merged_stage3, width=100, sort_dicts=True)
        new_block_body = (
            "# Auto-generated by prepare_phase_unified.py from union of prior "
            "phase winners.\n"
            f"{dict_name} = {dict_repr}\n"
            f"SIZE_BUCKETS = {buckets_repr}\n"
            f"STAGE3_OVERRIDES = {stage3_repr}\n"
        )
    else:
        dict_repr = pprint.pformat(merged, width=100, sort_dicts=True)
        new_block_body = (
            "# Auto-generated by prepare_phase_unified.py from union of prior "
            "phase winners.\n"
            f"{dict_name} = {dict_repr}\n"
        )

    new_src, n_subs = _EVOLVE_BLOCK_RE.subn(
        lambda m: m.group(1) + new_block_body + m.group(2),
        src,
        count=1,
    )
    if n_subs != 1:
        print(f"EVOLVE-BLOCK markers not found in {unified_file}", file=sys.stderr)
        sys.exit(1)
    unified_file.write_text(new_src)
    suffix = " (+ SIZE_BUCKETS, STAGE3_OVERRIDES)" if has_extras else ""
    print(f"wrote {unified_file.relative_to(pathlib.Path(root))} "
          f"({len(merged)} keys in EVOLVE-BLOCK){suffix}")
