"""
Materialize a standalone final_program.py from the phase5 winner plus all
inherited prior-phase winners.

Inputs:
  shared/baseline_params.py         BASELINE dict
  shared/phase4_best.json           inherited GLOBAL_OVERRIDES (1+2+3 unified)
  shared/phase4_buckets.json        inherited SIZE_BUCKETS
  shared/phase4_stage3.json         inherited STAGE3_OVERRIDES
  shared/has_objective_cache.json   SHA set used by needs_objective gating
  phase5_custom_subsolvers/openevolve_output/best/best_program.py
      CUSTOM_SUBSOLVERS, STAGE3_CUSTOM_SUBSOLVERS (Python literals only)

Output:
  final_program.py  — self-contained: no JSON loads, no relative imports.
                      Exposes BASELINE/GLOBAL_OVERRIDES/SIZE_BUCKETS/
                      STAGE3_OVERRIDES/CUSTOM_SUBSOLVERS/
                      STAGE3_CUSTOM_SUBSOLVERS/PHASE_LOCKED constants and
                      get_params(problem=None, stage=None) using the exact
                      phase5 merge logic.

Usage:
  python materialize_final.py [--output PATH] [--phase5-best PATH]
"""
import argparse
import importlib.util
import json
import pathlib
import pprint
import sys
import textwrap

_HERE = pathlib.Path(__file__).resolve().parent
_SHARED = _HERE / "shared"
_PHASE5_BEST = _HERE / "phase5_custom_subsolvers/openevolve_output/best/best_program.py"
_DEFAULT_OUT = _HERE / "final_program.py"


def _load_phase5_specs(phase5_path):
    """Import phase5 best_program just to read CUSTOM_SUBSOLVERS and
    STAGE3_CUSTOM_SUBSOLVERS. Those are static literals so the snapshot's
    broken _SHARED relative path does not matter — the JSON loads that fail
    inside the module only affect _PHASE4 / _PHASE4_BUCKETS / _PHASE4_STAGE3,
    which we re-read directly from shared/ here."""
    spec = importlib.util.spec_from_file_location("phase5_best", phase5_path)
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(_SHARED))
    spec.loader.exec_module(module)
    return module.CUSTOM_SUBSOLVERS, module.STAGE3_CUSTOM_SUBSOLVERS


def _format_buckets(buckets):
    lines = ["["]
    for upper, override in buckets:
        upper_src = "float('inf')" if upper is None else repr(upper)
        ov_src = pprint.pformat(override, width=100, sort_dicts=True)
        lines.append(f"    ({upper_src}, {ov_src}),")
    lines.append("]")
    return "\n".join(lines)


_TEMPLATE = '''\
"""
AUTO-GENERATED by materialize_final.py — DO NOT EDIT BY HAND.

Self-contained final CP-SAT parameter program. Bakes every inherited dict
from phase1..4 plus phase5 custom subsolvers. No JSON loads, no relative
imports — drop-in for final_verify.py / benchmark_final.py.

Source phase5 best_program:
  {phase5_rel}
"""

BASELINE = {baseline}

# Inherited from shared/phase4_best.json (union of phase1+2+3 winners + phase4
# unified pass).
GLOBAL_OVERRIDES = {global_overrides}

# Inherited from shared/phase4_buckets.json. Selected by num_constraints
# (first bucket whose upper > num_constraints wins).
SIZE_BUCKETS = {size_buckets}

# Inherited from shared/phase4_stage3.json. Applied only when
# stage == "stage3" and problem.is_outlier. NOTE: the current evaluator
# never passes stage="stage3" (small profile cascades stage1->stage2; large
# profile passes stage="large"), so this dict is dead code in practice.
STAGE3_OVERRIDES = {stage3_overrides}

# Phase5 custom subsolvers (always-on, gated by needs_objective /
# min_constraints / max_constraints).
CUSTOM_SUBSOLVERS = {custom_subsolvers}

# Phase5 stage3-only extra custom subsolvers (same dead-code caveat as
# STAGE3_OVERRIDES).
STAGE3_CUSTOM_SUBSOLVERS = {stage3_custom_subsolvers}

# SHAs whose original model has an objective. Used by needs_objective gating
# so an objective-requiring subsolver is not added to a feasibility-only
# model (which would make CP-SAT drop most of the portfolio).
OBJECTIVE_SHAS = frozenset({objective_shas})

# Phase5 final lock. Enforced last so nothing above can override it.
PHASE_LOCKED = {{
    "random_seed": 0,
    "num_search_workers": 8,
    "interleave_search": True,
}}


def _problem_has_objective(problem):
    if problem is None:
        return True
    sha = problem.get("sha")
    if sha is None:
        return problem.get("baseline_objective") is not None
    return sha in OBJECTIVE_SHAS


def _eligible(spec, problem):
    if spec.get("needs_objective") and not _problem_has_objective(problem):
        return False
    nc = int(problem.get("num_constraints") or 0) if problem else 0
    lo = spec.get("min_constraints")
    if lo is not None and nc < lo:
        return False
    hi = spec.get("max_constraints")
    if hi is not None and nc >= hi:
        return False
    return True


def _bucket_override(num_constraints):
    out = {{}}
    for upper, override in SIZE_BUCKETS:
        if num_constraints < upper:
            out.update(override)
            break
    return out


def _collect_specs(problem, stage):
    specs = [s for s in CUSTOM_SUBSOLVERS if _eligible(s, problem)]
    if stage == "stage3" and problem is not None and problem.get("is_outlier"):
        specs += [s for s in STAGE3_CUSTOM_SUBSOLVERS if _eligible(s, problem)]
    return specs


def _apply_custom_subsolvers(p, specs):
    if not specs:
        return
    sub_entries = []
    new_names = []
    for spec in specs:
        entry = {{"name": spec["name"]}}
        entry.update(spec.get("params") or {{}})
        sub_entries.append(entry)
        new_names.append(spec["name"])
    p["subsolver_params"] = sub_entries
    existing = list(p.get("extra_subsolvers") or [])
    for name in new_names:
        if name not in existing:
            existing.append(name)
    p["extra_subsolvers"] = existing


def get_params(problem=None, stage=None):
    p = dict(BASELINE)
    p.update(GLOBAL_OVERRIDES)
    if problem is not None:
        p.update(_bucket_override(int(problem.get("num_constraints") or 0)))
        if stage == "stage3" and problem.get("is_outlier"):
            p.update(STAGE3_OVERRIDES)
    _apply_custom_subsolvers(p, _collect_specs(problem, stage))
    p.update(PHASE_LOCKED)
    return p
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--output", default=str(_DEFAULT_OUT),
                    help=f"output path (default: {_DEFAULT_OUT.relative_to(_HERE)})")
    ap.add_argument("--phase5-best", default=str(_PHASE5_BEST),
                    help="phase5 best_program.py path")
    args = ap.parse_args()

    sys.path.insert(0, str(_SHARED))
    from baseline_params import BASELINE  # noqa: E402

    phase4_best = json.loads((_SHARED / "phase4_best.json").read_text())
    phase4_buckets_raw = json.loads((_SHARED / "phase4_buckets.json").read_text())
    phase4_buckets = [(None if u is None else u, ov) for u, ov in phase4_buckets_raw]
    phase4_stage3 = json.loads((_SHARED / "phase4_stage3.json").read_text())

    obj_cache_path = _SHARED / "has_objective_cache.json"
    objective_shas = set(json.loads(obj_cache_path.read_text()).get("with_objective") or [])

    custom_subsolvers, stage3_custom_subsolvers = _load_phase5_specs(
        pathlib.Path(args.phase5_best)
    )

    rendered = _TEMPLATE.format(
        phase5_rel=pathlib.Path(args.phase5_best).resolve().relative_to(_HERE),
        baseline=pprint.pformat(dict(BASELINE), width=100, sort_dicts=True),
        global_overrides=pprint.pformat(phase4_best, width=100, sort_dicts=True),
        size_buckets=_format_buckets(phase4_buckets),
        stage3_overrides=pprint.pformat(phase4_stage3, width=100, sort_dicts=True),
        custom_subsolvers=pprint.pformat(custom_subsolvers, width=100, sort_dicts=True),
        stage3_custom_subsolvers=pprint.pformat(stage3_custom_subsolvers, width=100, sort_dicts=True),
        objective_shas=pprint.pformat(sorted(objective_shas), width=100),
    )

    out = pathlib.Path(args.output)
    out.write_text(rendered)
    print(f"wrote {out.relative_to(_HERE)} "
          f"({len(BASELINE)} baseline + {len(phase4_best)} global + "
          f"{len(phase4_buckets)} buckets + {len(phase4_stage3)} stage3 + "
          f"{len(custom_subsolvers)} custom subsolvers + "
          f"{len(stage3_custom_subsolvers)} stage3 custom subsolvers)")


if __name__ == "__main__":
    main()
